version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang-test
    ports:
      - '3308:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  app:
    image: golang:1.23
    volumes:
      - .:/app
    working_dir: /app
    command: "go run main.go"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge



#docker-compose up -d
#docker-compose down